### ISSUE TITLE
Job Limitations

### ISSUE THREAD

**Issue by NateHiggs** [poke1337/zaz-issue-tracker#17]
- [x] Gang accountants need a gang leader
 - [x] SWAT needs a mayor

**Comment by poke1337** [comment]
This is done in the jobs file by adding the following code to a job-

	customCheck = function(ply)
		for i=1,#player.GetAll() do
			if player.GetAll()[i]:getDarkRPVar( "job" ) == "Mayor" then return true end
		end
		return false
	end,
	CustomCheckFailMsg = "There needs to be a Mayor.",
